# Generated by Django 5.0 on 2024-01-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the investment", max_length=30
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter the investment amount",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("MAD", "Moroccan Dirham"),
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                            ("DOT", "Polkadot"),
                            ("SOL", "Solana"),
                            ("ATOM", "Cosmos"),
                            ("MANA", "Decentraland"),
                            ("FLOW", "Flow"),
                        ],
                        default="EUR",
                        help_text="Select the currency",
                        max_length=5,
                    ),
                ),
                (
                    "date_invested",
                    models.DateField(help_text="Enter the date of the investment"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Provide a description of the investment (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Is this investment still active?"
                    ),
                ),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("Stock", "Stock"),
                            ("PE", "Private Equity"),
                            ("ETF", "ETF"),
                            ("Real Estate", "Real Estate"),
                            ("Life Insurance", "Life Insurance"),
                            ("Crypto", "Crypto"),
                            ("Other", "Other"),
                        ],
                        help_text="Select the type of investment",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Enter the source of the investment (e.g: 'Boursorama')",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
